// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Yami_SkipTitle","status":true,"description":"テストプレイ用にタイトルシーンを飛ばすことができます。","parameters":{}},
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"40","screenWidth":"1280","screenHeight":"720","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"canvas","alwaysDash":"off"}},
{"name":"AdjustPictureGraphical","status":true,"description":"ピクチャのグラフィカルな位置調整プラグイン。\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"グリッドサイズ":"48","テストマップID":"-1"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"false","ピクチャ番号の変数番号":"21","ポインタX座標の変数番号":"0","ポインタY座標の変数番号":"0","タッチ操作抑制":"false","戦闘中常にコモン実行":"false","無効スイッチ":"20"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"ALT_WindowTextMove","status":true,"description":"メッセージテキストの位置を調整","parameters":{"zahyou_X":"533","zahyou_Y":"7"}},
{"name":"PictureAnimation","status":true,"description":"ピクチャのアニメーションプラグイン","parameters":{"最初のセルに戻る":"true"}},
{"name":"BB_CustomSaveWindow","status":true,"description":"セーブウインドウ改造プラグイン","parameters":{"OutsideFrameColor":"0","OutsideFrameOpacity":"64","InsideFrameColor":"0","InsideFrameOpacity":"64","MaxItem":"1","Item0":"6","Item0Length":"300","Item1title":"","Item1":"0","Item2title":"所持金","Item2":"4","Item3title":"","Item3":"","Item4title":"","Item4":"","Item5":"7","ItemValue1":"44","ItemValue2":"51","ItemValue3":"3","ItemValue4":"4","ItemValue1unit":"","ItemValue2unit":"周目","ItemValue3unit":"","ItemValue4unit":"","TitleFramelength1":"110","TitleFramelength2":"110","TitleFramelength3":"110","TitleFramelength4":"110","CharacterPositionY":"6","CharacterOpacity":"0","LevelPositionY":"23","LevelOnOff":"0"}},
{"name":"TMItemCategoryEx","status":true,"description":"アイテムカテゴリの追加、削除をおこないます。","parameters":{"categoryList":"素材 調教 アップデート"}},
{"name":"GraphicalDesignMode","status":true,"description":"GUI画面デザインプラグイン\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"デザインモード":"false","自動保存":"false","モバイル版作成":"false","モバイル偽装":"false","ウィンドウ透過":"false","グリッドサイズ":"48","パディング":"0","フォントサイズ":"0","行の高さ":"0","背景透明度":"0","アイコンサイズ調整":"false","背景表示可否固定":"false","右クリックで消去":"false","メッセージウィンドウを無視":"false"}},
{"name":"mouse","status":true,"description":"","parameters":{}},
{"name":"FastForwardCustomize","status":false,"description":"イベント高速化調整プラグイン","parameters":{"イベント速度変数":"11"}},
{"name":"FacePicture","status":true,"description":"顔グラのピクチャ表示プラグイン","parameters":{}},
{"name":"UTA_CommonSave","status":true,"description":"共有のセーブデータを作成し、指定したスイッチ・変数の状態をセーブデータ間で共有します。","parameters":{"Target Switches":"11,40,141-180","Target Variables":"","Is Auto":"true","Auto on Gameover":"false","Show Trace":"false"}},
{"name":"CustomizeConfigDefault","status":true,"description":"オプションデフォルト値設定プラグイン","parameters":{"常時ダッシュ":"OFF","コマンド記憶":"OFF","BGM音量":"40","BGS音量":"40","ME音量":"40","SE音量":"40","常時ダッシュ消去":"ON","コマンド記憶消去":"ON","BGM音量消去":"OFF","BGS音量消去":"OFF","ME音量消去":"ON","SE音量消去":"OFF"}}
];
